### ISSUE TITLE
Unterkategorien einführen

### ISSUE THREAD

**Issue by chriswars** [d120/padman#17]
Es wäre cool wenn man Unterkategorien definieren könnte um die Liste kompakter zu halten (mehr als 7 Einträge werden ja unter einem Spoiler versteckt). So könnte man die Kategorie FSS zB unter UAs ablegen oder FIM unter Fachschaft usw.

**Comment by jlauinger** [comment]
:+1:

**Comment by max-weller** [comment]
Erledigt
