### ISSUE TITLE
 Notice: Undefined offset: 0 in /var/www/padman/private/index.php on line 159

### ISSUE THREAD

**Issue by jnhmn** [d120/padman#18]
Serveral broken PHP Files

https://www.fachschaft.informatik.tu-darmstadt.de/pad/?group=fachschaft&show=verleihkatalog:
 Notice: Undefined offset: 0 in /var/www/padman/private/showpad.php on line 5

**Comment by max-weller** [comment]
Das Pad gibt es nicht. Aber die Fehlermeldung, dass es das nicht gibt, ist jetzt wieder hübscher. :-)
