### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by maxklock** [d120/padman#28]
I tryed to install padman on my server, but I wasn't able to follow all instructions, because some of the files (e.g. update_groups.php) are missing. And the other thing is, that there is no index.php in the root folder. Do I need to use "public" as root folder?

When I link to public, I'm getting a "Pad not found" message. My etherpad-api has currentVersion 1.2.13 and is reachable with the apikey i've set in the config.inc.php. The Connection to the database is working fine.

**Comment by max-weller** [comment]
Indeed, the readme is outdated. You should use public and private as documentroots/aliases, and protect private with e.g. basic auth. The public folder is used for public shortlinks to pads.
update_groups.php was incorporated in the padmanctl.php, I think you can run `php padmanctl.php -R` instead.
I'll update the readme at some point...

**Comment by max-weller** [comment]
I think the readme is correct now.
